apiVersion: apps/v1
kind: Deployment
metadata:
  name: koyeb-html-test
  labels:
    app: koyeb-html-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koyeb-html-test
  template:
    metadata:
      labels:
        app: koyeb-html-test
        build-date: "20240101000000"  # مقدار پیش‌فرض که در pipeline جایگزین میشه
    spec:
      containers:
        - name: koyeb-html-test
          image: davoodazarirad/koyeb-html-test:latest
          ports:
            - containerPort: 80
