apiVersion: apps/v1
kind: Deployment
metadata:
  name: koyeb-html-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koyeb-html-test
  template:
    metadata:
      labels:
        app: koyeb-html-test
      annotations:
        deploy-time: "{{ .Values.deployTime | default \"manual-update\" }}"
    spec:
      containers:
        - name: html
          image: davoodazarirad/koyeb-html-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
