apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=Dockerfile"
          - "--context=git://github.com/Davoodazarirad/koyeb-html-test.git"
          - "--destination=docker.io/davoodazarirad/koyeb-html-test:latest"
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: dockerhub-secret
