name: Build and Deploy with Kaniko

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

    - name: Delete Previous Job (if any)
      run: |
        kubectl --kubeconfig=kubeconfig.yaml delete job kaniko-build-job --ignore-not-found

    - name: Trigger Kaniko Build Job
      run: |
        kubectl --kubeconfig=kubeconfig.yaml create -f .github/k8s/kaniko-build-job.yaml

    - name: Wait for Kaniko job to complete
      run: |
        kubectl --kubeconfig=kubeconfig.yaml wait --for=condition=complete --timeout=300s job/kaniko-build-job

    - name: Update Deployment to Trigger ArgoCD
      run: |
        kubectl --kubeconfig=kubeconfig.yaml apply -f .github/k8s/deployment.yaml
