name: Build and Deploy with Kaniko

on:
  push:
    branches:
      - main

jobs:
  trigger-kaniko-job:
    name: Trigger Kaniko Job on K8s
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml

      - name: Apply Kaniko Build Job
        run: |
          kubectl --kubeconfig=kubeconfig.yaml apply -f .github/k8s/kaniko-build-job.yaml
