name: Build and Deploy with Kaniko

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build Tag
        id: tag
        run: echo "DOCKER_TAG=build-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t docker.io/davoodazarirad/koyeb-html-test:${{ env.DOCKER_TAG }} .
          docker push docker.io/davoodazarirad/koyeb-html-test:${{ env.DOCKER_TAG }}

      - name: Apply Kubernetes Deployment
        run: |
          kubectl set image deployment/koyeb-html-test koyeb-html-test=docker.io/davoodazarirad/koyeb-html-test:${{ env.DOCKER_TAG }} --record
          kubectl rollout status deployment/koyeb-html-test
