name: Update Deployment to Trigger ArgoCD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'index.html'

jobs:
  update-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set build-date
      run: |
        DATE=$(date +%Y-%m-%dT%H:%M:%S)
        sed -i "s/build-date: \".*\"/build-date: \"$DATE\"/" deployment.yaml

    - name: Commit & Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Update build-date to trigger ArgoCD"
        git push
