name: Update Deployment to Trigger ArgoCD

on:
  workflow_dispatch:
  push:
    paths:
      - index.html

jobs:
  update-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set build-date
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Updating build date to $DATE"
          sed -i "s|build-date: .*|build-date: $DATE|" deployment.yaml
          sed -i "s|build-date: \".*\"|build-date: \"$DATE\"|" deployment.yaml

      - name: Setup Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit & Push
        run: |
          git add deployment.yaml
          git commit -m "Update build-date to trigger ArgoCD" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Davoodazarirad/koyeb-html-test.git HEAD:main
